name: student_sphere
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.0
  firebase_auth_web: ^5.11.2
  firebase_database: ^10.5.2
  flutter:
    sdk: flutter

  firebase_core: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/bg.jpeg
