// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB24Pwa559IbkPkNdYPtNUKPSDQmgr575E',
    authDomain: 'student-sphere-2e987.firebaseapp.com',
    databaseURL: 'https://student-sphere-2e987-default-rtdb.firebaseio.com',
    projectId: 'student-sphere-2e987',
    storageBucket: 'student-sphere-2e987.appspot.com',
    messagingSenderId: '96804929606',
    appId: '1:96804929606:web:16a4d18ad620f9459b0a47',
    measurementId: 'G-H83BS5719F'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpk8v91mpGrndkbIX39AZNairJNcPWhY4',
    appId: '1:96804929606:android:8f2be8d2f23e009c9b0a47',
    messagingSenderId: '96804929606',
    projectId: 'student-sphere-2e987',
    databaseURL: 'https://student-sphere-2e987-default-rtdb.firebaseio.com',
    storageBucket: 'student-sphere-2e987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpT-xaRVVCxvI3JZ1irSwdbqWil9lPVFU',
    appId: '1:96804929606:ios:cca4665815fa6b0f9b0a47',
    messagingSenderId: '96804929606',
    projectId: 'student-sphere-2e987',
    databaseURL: 'https://student-sphere-2e987-default-rtdb.firebaseio.com',
    storageBucket: 'student-sphere-2e987.appspot.com',
    iosBundleId: 'com.example.studentSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpT-xaRVVCxvI3JZ1irSwdbqWil9lPVFU',
    appId: '1:96804929606:ios:cca4665815fa6b0f9b0a47',
    messagingSenderId: '96804929606',
    projectId: 'student-sphere-2e987',
    databaseURL: 'https://student-sphere-2e987-default-rtdb.firebaseio.com',
    storageBucket: 'student-sphere-2e987.appspot.com',
    iosBundleId: 'com.example.studentSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB24Pwa559IbkPkNdYPtNUKPSDQmgr575E',
    appId: '1:96804929606:web:9479c767ca7a86ff9b0a47',
    messagingSenderId: '96804929606',
    projectId: 'student-sphere-2e987',
    authDomain: 'student-sphere-2e987.firebaseapp.com',
    databaseURL: 'https://student-sphere-2e987-default-rtdb.firebaseio.com',
    storageBucket: 'student-sphere-2e987.appspot.com',
    measurementId: 'G-JGY1BWG978',
  );
}
